/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "liyqttumazsyherzzrca"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeXF0dHVtYXpzeWhlcnp6cmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4OTU1NTQsImV4cCI6MjA4OTQ3MTU1NH0.VN--vmjs3pKmSkv72VwIEupnXKNeK-2k3V1QCo5i3RQ"